version: "3"
services:
  communitysim:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: detoks_community_sim
    container_name: detoks_community_sim
    environment:
      NUM_NODES: ${NUM_NODES:-1}
      TIMEOUT: ${TIMEOUT:-20}
      MAX_NUM_PEERS: ${MAX_NUM_PEERS:-3}
      COMMUNITY_ID: ${COMMUNITY_ID:-98758cf7ca9238ccc33329384902d2938f348723}
    volumes:
      - ./torrents/:/app
      - ./communitysim.py:/communitysim.py
